apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pertisk-kube.fullname" . }}-auth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pertisk-kube.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.app.auth.username | default "admin" | b64enc | quote }}
  password: {{ required "app.auth.password is required" .Values.app.auth.password | b64enc | quote }}
  jwt-secret: {{ required "app.auth.jwtSecret is required" .Values.app.auth.jwtSecret | b64enc | quote }}
